# Generated by Django 3.2.8 on 2021-11-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='system_ud',
            new_name='system_id',
        ),
        migrations.AddField(
            model_name='measurement',
            name='interval',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
    ]
