# Generated by Django 3.2.8 on 2021-11-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='ip_v4',
        ),
        migrations.RemoveField(
            model_name='target',
            name='ip_v6',
        ),
        migrations.AddField(
            model_name='target',
            name='address_v4',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='target',
            name='address_v6',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[('ping', 'Ping'), ('traceroute', 'Traceroute'), ('dns', 'Dns'), ('sslcert', 'Sslcert'), ('http', 'Http'), ('ntp', 'Ntp')], max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='asn_v4',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='target',
            name='asn_v6',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='target',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='target',
            name='prefix_v4',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='target',
            name='prefix_v6',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
