# Generated by Django 3.2.8 on 2021-11-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0002_auto_20211107_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='target',
            name='target_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
