# Generated by Django 3.2.8 on 2021-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0003_auto_20211107_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='address_v4',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='address_v6',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='asn_v4',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='asn_v6',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='prefix_v4',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='prefix_v6',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
