# Generated by Django 3.2.8 on 2021-11-11 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPlatform',
            fields=[
                ('notification_platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_platform_name', models.CharField(max_length=100)),
                ('notification_platform_configuration', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
