# Generated by Django 3.2.8 on 2022-01-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationplatform',
            name='user',
        ),
    ]
