version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - ./data/postgress:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
  
  ai_server:
    build: ./AnomolyDetectionServer
    restart: always
    environment:
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - backend
      - mongo

  be_server:
      build: ./Backend
      restart: always
      environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      command: python manage.py runserver 0.0.0.0:8000
      networks:
        - backend

networks:
  backend:
    driver: ipvlan
  mongo:
    driver: ipvlan
