version: "3.9"

services:
  db:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  be:
    build: ./backend
    restart: always
    container_name: backend
    command: >
        sh -c "python user.py
        && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SUPERUSER_PASSWORD=password
    depends_on:
      - db
  ai:
    build: ./anomalydetection
    restart: always
    container_name: artificial-intelligence
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - ./anomalydetection:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  fe:
    build: ./frontend
    restart: always
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/code
    depends_on:
      - be
