# Generated by Django 3.2.8 on 2021-11-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
                ('probe_id', models.IntegerField(unique=True)),
                ('prefix_v4', models.CharField(blank=True, default='', max_length=128)),
                ('prefix_v6', models.CharField(blank=True, default='', max_length=128)),
                ('ip_v4', models.CharField(blank=True, default='', max_length=128)),
                ('ip_v6', models.CharField(blank=True, default='', max_length=128)),
                ('asn_v4', models.CharField(blank=True, default='', max_length=128)),
                ('asn_v6', models.CharField(blank=True, default='', max_length=128)),
                ('host', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('measurement_type', models.CharField(choices=[('Ping', 'Ping'), ('Traceroute', 'Traceroute'), ('Dns', 'Dns'), ('Sslcert', 'Sslcert'), ('Http', 'Http'), ('Ntp', 'Ntp')], max_length=10)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.target')),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('alert_configuration_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_configuration_type', models.CharField(max_length=100)),
                ('alert_configuration', models.JSONField()),
                ('measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Warning', 'Warning'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Critical', max_length=10)),
                ('description', models.TextField()),
                ('feedback', models.BooleanField(null=True)),
                ('alert_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.alertconfiguration')),
            ],
        ),
    ]
