# Generated by Django 3.2.9 on 2021-11-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('anomaly_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('feedback', models.BooleanField(null=True)),
                ('alert_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.alertconfiguration')),
            ],
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
