# Generated by Django 3.2.9 on 2021-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0002_auto_20211130_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='is_alert',
            field=models.BooleanField(default=False),
        ),
    ]
