# Generated by Django 3.2.8 on 2021-11-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0003_alter_alertconfiguration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.CharField(choices=[('Extern', 'Extern'), ('Probe', 'Probe')], default='Probe', max_length=10),
        ),
    ]
