# Generated by Django 3.2.8 on 2021-11-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0001_initial'),
        ('alert_configuration', '0004_target_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfiguration',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ripe_atlas.measurement'),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
