# Generated by Django 3.2.8 on 2021-11-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0005_auto_20211106_1942'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alertconfiguration',
            constraint=models.UniqueConstraint(fields=('user', 'measurement', 'alert_configuration_type'), name='unique_user_alert_configuration_on_measurement'),
        ),
    ]
