# Generated by Django 3.2.8 on 2022-03-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0007_alter_asn_as_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='response',
        ),
    ]
