# Generated by Django 3.2.8 on 2021-11-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPlatform',
            fields=[
                ('notification_platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_platform_name', models.CharField(max_length=100)),
                ('notification_platform_configuration', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('probe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix_v4', models.CharField(blank=True, default='', max_length=128)),
                ('prefix_v6', models.CharField(blank=True, default='', max_length=128)),
                ('ip_v4', models.CharField(blank=True, default='', max_length=128)),
                ('ip_v6', models.CharField(blank=True, default='', max_length=128)),
                ('asn_v4', models.CharField(blank=True, default='', max_length=128)),
                ('asn_v6', models.CharField(blank=True, default='', max_length=128)),
                ('host', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RipeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ripe_api_token', models.UUIDField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('measurement_type', models.CharField(choices=[('Ping', 'Ping'), ('Traceroute', 'Traceroute'), ('Dns', 'Dns'), ('Sslcert', 'Sslcert'), ('Http', 'Http'), ('Ntp', 'Ntp')], max_length=10)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.probe')),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('alert_configuration_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_configuration_type', models.CharField(max_length=100)),
                ('alert_configuration', models.JSONField()),
                ('measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Warning', 'Warning'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Critical', max_length=10)),
                ('description', models.TextField()),
                ('feedback', models.BooleanField(null=True)),
                ('alert_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.alertconfiguration')),
            ],
        ),
    ]
