# Generated by Django 3.2.8 on 2021-11-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_configuration',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='measurement_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='probe',
        ),
        migrations.DeleteModel(
            name='NotificationPlatform',
        ),
        migrations.RemoveField(
            model_name='ripeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertConfiguration',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Probe',
        ),
        migrations.DeleteModel(
            name='RipeUser',
        ),
    ]
