# Generated by Django 3.2.8 on 2021-11-11 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ripe_atlas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('alert_configuration_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_configuration_type', models.CharField(max_length=100)),
                ('alert_configuration', models.JSONField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ripe_atlas.measurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Warning', 'Warning'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Critical', max_length=10)),
                ('description', models.TextField()),
                ('feedback', models.BooleanField(null=True)),
                ('alert_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.alertconfiguration')),
            ],
        ),
        migrations.AddConstraint(
            model_name='alertconfiguration',
            constraint=models.UniqueConstraint(fields=('user', 'measurement', 'alert_configuration_type'), name='unique_user_alert_configuration_on_measurement'),
        ),
    ]
