# Generated by Django 3.2.9 on 2021-12-02 14:07

import alert_configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0003_anomaly_is_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='datetime',
            field=models.BigIntegerField(default=alert_configuration.models.current_unixtime),
        ),
    ]
