# Generated by Django 3.2.9 on 2021-12-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0004_anomaly_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='feedback',
            new_name='label',
        ),
    ]
