# Generated by Django 3.2.8 on 2022-03-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0005_rename_feedback_anomaly_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='anomaly',
            old_name='anomaly_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='alert_configuration',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='is_alert',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='label',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='anomaly_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='asn_error',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='detection_method_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='ip_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='measurement_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='medium_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='prediction_value',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='AlertConfiguration',
        ),
        migrations.AddField(
            model_name='feedback',
            name='anomaly_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.anomaly'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='asn_settings_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.asn'),
        ),
    ]
