# Generated by Django 3.2.8 on 2022-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0006_auto_20220314_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='as_number',
            field=models.IntegerField(null=True),
        ),
    ]
