# Generated by Django 3.2.8 on 2022-03-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_configuration', '0008_rename_feedback_feedback_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='anomaly_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert_configuration.anomaly', unique=True),
        ),
    ]
