# Generated by Django 3.2.8 on 2021-11-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_ud', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('target', 'Target'), ('anchor', 'Anchor')], default='anchor', max_length=10)),
                ('probe_id', models.IntegerField(unique=True)),
                ('prefix_v4', models.CharField(default=None, max_length=128, null=True)),
                ('prefix_v6', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('address_v4', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('address_v6', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('asn_v4', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('asn_v6', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('host', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('ping', 'Ping'), ('traceroute', 'Traceroute'), ('dns', 'Dns'), ('sslcert', 'Sslcert'), ('http', 'Http'), ('ntp', 'Ntp')], max_length=10)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ripe_atlas.system')),
            ],
        ),
    ]
