# Generated by Django 3.2.8 on 2021-11-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0002_auto_20211113_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='probe_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
