# Generated by Django 3.2.9 on 2021-12-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0003_alter_system_probe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('anchor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix_v4', models.CharField(default=None, max_length=128, null=True)),
                ('prefix_v6', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('ip_v4', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('ip_v6', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('fqdn', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asn',
            fields=[
                ('asn', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='system',
        ),
        migrations.DeleteModel(
            name='System',
        ),
        migrations.AddField(
            model_name='anchor',
            name='asn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ripe_atlas.asn'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='anchor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ripe_atlas.anchor'),
            preserve_default=False,
        ),
    ]
