# Generated by Django 3.2.9 on 2021-12-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ripe_atlas', '0004_auto_20211208_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor',
            name='prefix_v4',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='prefix_v6',
        ),
    ]
