# Generated by Django 3.2.8 on 2021-11-06 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripeuser',
            name='initial_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimezoneConfiguration',
            fields=[
                ('timezone_id', models.AutoField(primary_key=True, serialize=False)),
                ('timezone', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('usage', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timezone_configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
