# Generated by Django 3.2.8 on 2021-11-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20211106_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripeuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ripe_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
